image: gradle:8.2-jdk11
stages:
  - package
  - build
  - test

package:
  stage: package
  script:
    - make package
  artifacts:
    expire_in: 1hr
    paths:
      - /

build:
  image: openjdk:11.0.1-jre
  stage: build
  script:
    - make build
  artifacts:
    expire_in: 1hr
    paths:
      - /

test:
  image: openjdk:11.0.1-jre
  stage: test
  script:
    - make test
  artifacts:
    expire_in: 1hr
    paths:
      - /

