/*
 * This source file was generated by the Gradle 'init' task
 */
package fundamentals.kata

import fundamentals.kata.game.Game

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

fun main() {
    println(App().greeting)
    println()
    // Run the game demo
    Game.main(emptyArray())
}
